atividade-web2/config/routes.rb
Rails.application.routes.draw do
  resources :blog_legals
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

atividade-web2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

atividade-web2/app/models/blog_legal.rb
class BlogLegal < ApplicationRecord
end

atividade-web2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

atividade-web2/app/controllers/blog_legals_controller.rb
class BlogLegalsController < ApplicationController
  before_action :set_blog_legal, only: [:show, :edit, :update, :destroy]

  # GET /blog_legals
  # GET /blog_legals.json
  def index
    @blog_legals = BlogLegal.all
  end

  # GET /blog_legals/1
  # GET /blog_legals/1.json
  def show
  end

  # GET /blog_legals/new
  def new
    @blog_legal = BlogLegal.new
  end

  # GET /blog_legals/1/edit
  def edit
  end

  # POST /blog_legals
  # POST /blog_legals.json
  def create
    @blog_legal = BlogLegal.new(blog_legal_params)

    respond_to do |format|
      if @blog_legal.save
        format.html { redirect_to @blog_legal, notice: 'Blog legal was successfully created.' }
        format.json { render :show, status: :created, location: @blog_legal }
      else
        format.html { render :new }
        format.json { render json: @blog_legal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_legals/1
  # PATCH/PUT /blog_legals/1.json
  def update
    respond_to do |format|
      if @blog_legal.update(blog_legal_params)
        format.html { redirect_to @blog_legal, notice: 'Blog legal was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_legal }
      else
        format.html { render :edit }
        format.json { render json: @blog_legal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_legals/1
  # DELETE /blog_legals/1.json
  def destroy
    @blog_legal.destroy
    respond_to do |format|
      format.html { redirect_to blog_legals_url, notice: 'Blog legal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_legal
      @blog_legal = BlogLegal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_legal_params
      params.require(:blog_legal).permit(:titulo, :text)
    end
end

atividade-web2/app/helpers/application_helper.rb
module ApplicationHelper
end

atividade-web2/app/helpers/blog_legals_helper.rb
module BlogLegalsHelper
end

atividade-web2/app/views/blog_legals/_form.html.erb
<%= form_with(model: blog_legal, local: true) do |form| %>
  <% if blog_legal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog_legal.errors.count, "error") %> prohibited this blog_legal from being saved:</h2>

      <ul>
        <% blog_legal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

atividade-web2/app/views/blog_legals/edit.html.erb
<h1>Editing Blog Legal</h1>

<%= render 'form', blog_legal: @blog_legal %>

<%= link_to 'Show', @blog_legal %> |
<%= link_to 'Back', blog_legals_path %>

atividade-web2/app/views/blog_legals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blog Legals</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_legals.each do |blog_legal| %>
      <tr>
        <td><%= blog_legal.titulo %></td>
        <td><%= blog_legal.text %></td>
        <td><%= link_to 'Show', blog_legal %></td>
        <td><%= link_to 'Edit', edit_blog_legal_path(blog_legal) %></td>
        <td><%= link_to 'Destroy', blog_legal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog Legal', new_blog_legal_path %>

atividade-web2/app/views/blog_legals/new.html.erb
<h1>New Blog Legal</h1>

<%= render 'form', blog_legal: @blog_legal %>

<%= link_to 'Back', blog_legals_path %>

atividade-web2/app/views/blog_legals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @blog_legal.titulo %>
</p>

<p>
  <strong>Text:</strong>
  <%= @blog_legal.text %>
</p>

<%= link_to 'Edit', edit_blog_legal_path(@blog_legal) %> |
<%= link_to 'Back', blog_legals_path %>

atividade-web2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AtividadeWeb2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>